# Generated by Django 6.1.1 on 2026-09-29 14:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name'], 'verbose_name': 'Lớp học', 'verbose_name_plural': 'Lớp học'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['student', 'subject'], 'verbose_name': 'Điểm', 'verbose_name_plural': 'Điểm'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['student_code'], 'verbose_name': 'Sinh viên', 'verbose_name_plural': 'Sinh viên'},
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.CharField(max_length=50, verbose_name='Khóa học'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Tên lớp'),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm'),
        ),
        migrations.AlterField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.student', verbose_name='Sinh viên'),
        ),
        migrations.AlterField(
            model_name='score',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Môn học'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.classroom', verbose_name='Lớp'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã sinh viên'),
        ),
    ]
